#!/bin/sh

# example of SVN/Jenkins post-commit hook for dosocs2

#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#   [3] TXN-NAME     (the name of the transaction that has become REV)
#

REPOS="$1"
#REV="$2"
#TXN_NAME="$3"

# url escape
NEWREPOS=$(python2 -c "\
import sys; print '$REPOS'\
.replace('%', '%25')\
.replace('/', '%2F')\
.replace(' ', '%20')\
.replace('\"', '%22')\
.replace('-', '%2D')\
.replace('.', '%2E')\
.replace('<', '%3C')\
.replace('>', '%3E')\
.replace('\\\\', '%5C')\
.replace('^', '%5E')\
.replace('_', '%5F')\
.replace('\`', '%60')\
.replace('{', '%7B')\
.replace('|', '%7C')\
.replace('}', '%7D')\
.replace('~', '%7E')")

/usr/bin/wget \
  --header "Content-Type:text/plain;charset=UTF-8" \
  --output-document "-" \
  --timeout=2 --user=socs --password=socs --auth-no-challenge \
  --post-data "" \
  "http://localhost:9002/job/dosocs2-svn/buildWithParameters?token=socs&TARGET%5FPATH=$NEWREPOS"
