drop view if exists v_license_approved_names cascade;
drop view if exists v_creators cascade;
drop view if exists v_annotations cascade;
drop view if exists v_documents_creators cascade;
drop view if exists v_documents_files cascade;
drop view if exists v_documents_packages cascade;
drop view if exists v_documents cascade;
drop view if exists v_documents_unofficial_licenses cascade;
drop view if exists v_external_refs cascade;
drop view if exists v_file_contributors cascade;
drop view if exists v_files_licenses cascade;
drop view if exists v_packages_all_licenses_in_files cascade;
drop view if exists v_relationships cascade;
drop view if exists v_rel_contains cascade;
drop view if exists v_rel_contained_by cascade;
drop view if exists v_rel_describes cascade;
drop view if exists v_rel_described_by cascade;
drop view if exists v_dupes;
